#!/bin/bash

shareDir="/home/qinyuan/share"
mallDir="$shareDir/mall"
if [ -d "$mallDir" ]; then
    dl $mallDir
fi

mkdir $mallDir
cp -r *.html css js lib $mallDir

cd $shareDir

zipFile="mall.zip"
if [ -f "$zipFile" ]; then
    dl $zipFile
fi
zip -r $zipFile mall/
